language: node_js
node_js:
  - '8'
services:
  - mongodb
addons:
  code_climate:
    repo_token: '8c232e646237e391c746607753ca938d4ba43e5ed31206e75437a1ef041a6b51'
notifications:
  email: false
before_script:
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
